<a href="https://colab.research.google.com/github/MudasirH-coder/Mudasir-demo/blob/main/Ecommerce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ecommerce (Malti-Gauri) Data Analysis

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
orders = pd.read_csv('/customers.csv')
orders.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,created_at
0,1,Sai,Sharma,ssharma251@yahoo.com,9117550026,Jaipur,Rajasthan,477442,2024-06-09
1,2,Aarav,Kulkarni,akulkarni715@example.in,9319300868,Pune,Maharashtra,859358,2023-09-26
2,3,Saanvi,Khanna,skhanna722@gmail.com,9022021263,Kolkata,West Bengal,636760,2023-10-13
3,4,Ishaan,Kapoor,ikapoor168@example.in,9396568720,Ahmedabad,Gujarat,640957,2022-08-06
4,5,Kiara,Nair,knair147@outlook.com,9175745391,Patna,Bihar,800167,2023-03-09

How many total orders have been placed ?

In [ ]:
orders = pd.read_csv('/orders.csv')
orders.head()

,order_id,customer_id,order_datetime,payment_method,order_status,shipping_city,shipping_state,shipping_pincode,order_total
0,1,326,2025-03-09 14:44:00,COD,DELIVERED,Delhi,Delhi,848534,34677.49
1,2,214,2024-06-15 04:32:00,UPI,DELIVERED,Bengaluru,Karnataka,364268,2309.37
2,3,67,2025-06-09 16:07:00,Debit Card,DELIVERED,Patna,Bihar,690607,6877.02
3,4,17,2024-06-09 17:23:00,COD,CONFIRMED,Delhi,Delhi,463589,1529.48
4,5,210,2024-04-22 03:23:00,Credit Card,PLACED,Kochi,Kerala,753052,5395.26

Analysing the total number of the id's

In [ ]:
total_orders = orders['order_id'].nunique()
print(total_orders)

800

Q; WHAT IS THE TOTAL REVENUE GENERATED BY THE PLATFORM

In [ ]:
orders.head(3)

,order_id,customer_id,order_datetime,payment_method,order_status,shipping_city,shipping_state,shipping_pincode,order_total
0,1,326,2025-03-09 14:44:00,COD,DELIVERED,Delhi,Delhi,848534,34677.49
1,2,214,2024-06-15 04:32:00,UPI,DELIVERED,Bengaluru,Karnataka,364268,2309.37
2,3,67,2025-06-09 16:07:00,Debit Card,DELIVERED,Patna,Bihar,690607,6877.02

**bold text**Ecommerce company generated a total_revenue (orders_total)

In [ ]:
total_revenue=orders["order_total"].sum().round(2)
print(total_revenue)

14371866.37

What is the Average order value (AOV)

In [ ]:
orders["order_total"].mean()

np.float64(17964.8329625)

In [ ]:
###Used a round function

orders["order_total"].mean().round(2)

np.float64(17964.83)

How many Unique Customers have placed orders?

In [ ]:
customers=pd.read_csv('/customers.csv')
customers.head(5)

,customer_id,first_name,last_name,email,phone,city,state,pincode,created_at
0,1,Sai,Sharma,ssharma251@yahoo.com,9117550026,Jaipur,Rajasthan,477442,2024-06-09
1,2,Aarav,Kulkarni,akulkarni715@example.in,9319300868,Pune,Maharashtra,859358,2023-09-26
2,3,Saanvi,Khanna,skhanna722@gmail.com,9022021263,Kolkata,West Bengal,636760,2023-10-13
3,4,Ishaan,Kapoor,ikapoor168@example.in,9396568720,Ahmedabad,Gujarat,640957,2022-08-06
4,5,Kiara,Nair,knair147@outlook.com,9175745391,Patna,Bihar,800167,2023-03-09

In [ ]:
customers["customer_id"].nunique()

350

In [ ]:
###Analysing the customers full_name and last_name from the datasets
customers["full_name"]=customers["first_name"]+" "+customers["last_name"]
customers.head(5)

,customer_id,first_name,last_name,email,phone,city,state,pincode,created_at,full_name
0,1,Sai,Sharma,ssharma251@yahoo.com,9117550026,Jaipur,Rajasthan,477442,2024-06-09,Sai Sharma
1,2,Aarav,Kulkarni,akulkarni715@example.in,9319300868,Pune,Maharashtra,859358,2023-09-26,Aarav Kulkarni
2,3,Saanvi,Khanna,skhanna722@gmail.com,9022021263,Kolkata,West Bengal,636760,2023-10-13,Saanvi Khanna
3,4,Ishaan,Kapoor,ikapoor168@example.in,9396568720,Ahmedabad,Gujarat,640957,2022-08-06,Ishaan Kapoor
4,5,Kiara,Nair,knair147@outlook.com,9175745391,Patna,Bihar,800167,2023-03-09,Kiara Nair

In [ ]:
customers['full_name'].value_counts()

full_name
Ayaan Chatterjee    3
Saanvi Nair         3
Tara Gupta          3
Aarya Rastogi       3
Sai Sharma          3
                   ..
Kabir Mehta         1
Sai Mishra          1
Meera Sharma        1
Kartik Mehta        1
Saanvi Chawla       1
Name: count, Length: 299, dtype: int64

In [ ]:
###Same customers who have created the same accounts in multi-time

name_counts = customers["full_name"].value_counts().reset_index(name='count')
name_analysis = name_counts[name_counts["count"] > 1]
name_analysis

           full_name  count
0   Ayaan Chatterjee      3
1        Saanvi Nair      3
2         Tara Gupta      3
3      Aarya Rastogi      3
4         Sai Sharma      3
5        Riya Khanna      3
6          Ira Mehta      3
7       Dhruv Pillai      2
8         Mira Gupta      2
9       Virat Khanna      2
10      Aisha Shetty      2
11    Ayaan Banerjee      2
12       Myra Mishra      2
13    Arjun Bhandari      2
14       Aarya Joshi      2
15     Ananya Pillai      2
16       Rudra Verma      2
17       Aisha Patel      2
18       Kabir Desai      2
19      Aarohi Joshi      2
20     Aarav Trivedi      2
21        Sai Kapoor      2
22    Sai Chatterjee      2
23       Pranav Khan      2
24       Kabir Patel      2
25        Myra Reddy      2
26     Arnav Goswami      2
27       Kavya Yadav      2
28     Tara Kulkarni      2
29    Anika Banerjee      2
30       Krish Gupta      2
31        Myra Joshi      2
32      Aisha Chawla      2
33    Aarya Banerjee      2
34    Rudra Kulkarni      2
35       Aarya Verma      2
36      Riya Rastogi      2
37     Anay Kulkarni      2
38    Reyansh Tiwari      2
39      Ayaan Khanna      2
40    Meera Bhandari      2
41       Saanvi Iyer      2
42       Virat Yadav      2
43        Kiara Nair      2

In [ ]:
customers["full_name"].nunique()

299

In [ ]:
###Analysis a  person with same name who is in the dataset

customers[customers["full_name"]=="Sai Sharma"]

,customer_id,first_name,last_name,email,phone,city,state,pincode,created_at,full_name
0,1,Sai,Sharma,ssharma251@yahoo.com,9117550026,Jaipur,Rajasthan,477442,2024-06-09,Sai Sharma
262,263,Sai,Sharma,ssharma641@gmail.com,9726403826,Patna,Bihar,520357,2022-04-27,Sai Sharma
268,269,Sai,Sharma,ssharma574@gmail.com,9233172206,Kochi,Kerala,650090,2023-01-28,Sai Sharma